const fakeData = {
  count: 15,
  next: 'http://kddn.app/api/customers/?limit=10&offset=10',
  previous: null,
  results: [
    {
      store: 'quang1',
      buyer_user_id: 468698,
      email: 'q18@gmail.com',
      name: 'q18',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang1',
      buyer_user_id: 112412,
      email: 'q1@gmail.com',
      name: 'qqqq',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang1',
      buyer_user_id: 12313,
      email: 'q13@gmail.com',
      name: 'q13',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang2',
      buyer_user_id: 125125,
      email: 'q21@gmail.com',
      name: 'q21',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang2',
      buyer_user_id: 567475471,
      email: 'q25@gmail.com',
      name: 'q25',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang2',
      buyer_user_id: 633734737,
      email: 'q26@gmail.com',
      name: 'q26',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang1',
      buyer_user_id: 151566,
      email: 'q15@gmail.com',
      name: 'q15',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang2',
      buyer_user_id: 6948601,
      email: 'q24@gmail.com',
      name: 'q24',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang1',
      buyer_user_id: 75858,
      email: 'q16@gmail.com',
      name: 'q16',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
    {
      store: 'quang1',
      buyer_user_id: 1245151,
      email: 'q14@gmail.com',
      name: 'q14',
      first_line: null,
      second_line: null,
      city: null,
      state: null,
      zip_code: null,
      formatted_address: null,
      country_iso: null,
      order_count: 0,
    },
  ],
}
export default fakeData
